// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdJr46Qnp0uCIz6s0FCPtZf6OMS81Hrxw',
    appId: '1:945060030346:web:ae0169335e40ffc1250a73',
    messagingSenderId: '945060030346',
    projectId: 'fir-act14-32715',
    authDomain: 'fir-act14-32715.firebaseapp.com',
    storageBucket: 'fir-act14-32715.firebasestorage.app',
    measurementId: 'G-8VJ6PEXEEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGBy8vkdSq9g7Y39z4kbZs0FS6Yt5tZ-Q',
    appId: '1:945060030346:android:1c3684907e682ff8250a73',
    messagingSenderId: '945060030346',
    projectId: 'fir-act14-32715',
    storageBucket: 'fir-act14-32715.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl3M3QEOcVMX0HnWzkBVjmqIJxgxemyao',
    appId: '1:945060030346:ios:e13e5e6d19886cc2250a73',
    messagingSenderId: '945060030346',
    projectId: 'fir-act14-32715',
    storageBucket: 'fir-act14-32715.firebasestorage.app',
    iosBundleId: 'com.example.act14Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl3M3QEOcVMX0HnWzkBVjmqIJxgxemyao',
    appId: '1:945060030346:ios:e13e5e6d19886cc2250a73',
    messagingSenderId: '945060030346',
    projectId: 'fir-act14-32715',
    storageBucket: 'fir-act14-32715.firebasestorage.app',
    iosBundleId: 'com.example.act14Firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdJr46Qnp0uCIz6s0FCPtZf6OMS81Hrxw',
    appId: '1:945060030346:web:b0f401d896da0c4c250a73',
    messagingSenderId: '945060030346',
    projectId: 'fir-act14-32715',
    authDomain: 'fir-act14-32715.firebaseapp.com',
    storageBucket: 'fir-act14-32715.firebasestorage.app',
    measurementId: 'G-00WRXFS4RJ',
  );
}
